# Generated by Django 5.0 on 2025-04-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_draggroup_allow_member_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragqueen',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
