# Generated by Django 5.0 on 2025-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dragqueen_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragqueen',
            name='youtube_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
